version: '2.4'
services:
  xwiki:
    image: "xwiki:13.3-postgres-tomcat"
    container_name: xwiki-postgres-tomcat
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_USER: xwiki
      DB_PASSWORD: xwiki
      DB_DATABASE: xwiki
      DB_HOST: xwiki-postgres-db
    volumes:
      - ./volumes/xwiki-data:/usr/local/xwiki
  db:
    image: "postgres:12-alpine"
    container_name: xwiki-postgres-db
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_ROOT_PASSWORD=xwiki
      - POSTGRES_PASSWORD=xwiki
      - POSTGRES_USER=xwiki
      - POSTGRES_DB=xwiki
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
  nexus:
    image: sonatype/nexus3:3.32.0
    container_name: xwiki-nexus
    volumes:
      - ./volumes/nexus-data:/nexus-data
    ports:
      - "8081:8081"      
    environment:
      - POSTGRES_ROOT_PASSWORD=xwiki
  keycloak:
    image: quay.io/keycloak/keycloak:14.0.0
    container_name: xwiki-keycloak
    ports:
      - "8090:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
